````markdown
```shell
cat /root/hosts
[servers]
controlplane env=prod
node01 env=dev
```

```yaml
---
- name: MOTD Push
  hosts: servers
  vars:
  gather_facts: True
  become: True
  tasks:

  - name: Debug env variables
    debug:
      var: env

  - name: Push over the file if prod
    copy:
      src: /root/prod_motd
      dest: "/etc/motd"
    when: '"prod" in env'

  - name: Push over the file if dev
    copy:
      src: /root/dev_motd
      dest: "/etc/motd"
    when: '"dev" in env'
```
````

